version: 0.6.0.{build}
image: Visual Studio 2019
environment:
  SonarCloudToken:
    secure: mLdHKzO+1g4EkLf8DUXXWbbKWMWYswpke7N8W2Leb2Yl33jWjL//HTHqBW3k1/Ky
install:
- ps: dotnet tool install --global dotnet-sonarscanner
build_script:
- set JAVA_HOME=C:\Program Files\Java\jdk11
- set PATH=%JAVA_HOME%\bin;%PATH%
- ps: >-
    dotnet sonarscanner begin /d:"sonar.login=$env:SonarCloudToken" /d:"sonar.host.url=https://sonarcloud.io" /k:"jorgeyanesdiez_HueUpdater" /o:"jorgeyanesdiez" /v:"0.6" /d:"sonar.cs.opencover.reportsPaths=./build/coverage.opencover.xml"

    dotnet build
test_script:
- ps: >-
    dotnet test --results-directory "./build" --logger "trx;LogFileName=tests.vstest.trx" /p:"CollectCoverage=true" /p:"CoverletOutputFormat=opencover" /p:"CoverletOutput=../build/"

    dotnet sonarscanner end /d:"sonar.login=$env:SonarCloudToken"