version: '{build}'
image: Visual Studio 2022
environment:
  SonarCloudToken:
    secure: mLdHKzO+1g4EkLf8DUXXWbbKWMWYswpke7N8W2Leb2Yl33jWjL//HTHqBW3k1/Ky
install:
- ps: >-
    dotnet tool install --global coverlet.console

    dotnet tool install --global dotnet-sonarscanner
build_script:
- set JAVA_HOME=C:\Program Files\Java\jdk17
- set PATH=%JAVA_HOME%\bin;%PATH%
- ps: >-
    dotnet sonarscanner begin /d:sonar.login="$env:SonarCloudToken" /d:sonar.host.url="https://sonarcloud.io" /k:"jorgeyanesdiez_HueUpdater" /o:"jorgeyanesdiez" /d:sonar.cs.opencover.reportsPaths="coverage.xml"


    dotnet build --no-incremental
test_script:
- ps: >-
    coverlet .\HueUpdaterTest\bin\Debug\net6.0\HueUpdaterTest.dll --target "dotnet" --targetargs "test --no-build" -f="opencover" -o="coverage.xml"


    dotnet sonarscanner end /d:sonar.login="$env:SonarCloudToken"